#travis cio
language: python
os:
  - linux
  - osx
  - windows

matrix:
    include:
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: false
        - python: 3.8
          dist: xenial
          sudo: false
install:
  - "pip3 install ."
script:
  - "python zipfly/test.py"
sudo: false
