#travis cio
language: python
os:
  - linux
matrix:
  include:
    - dist: xenial
    - dist: trusty
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip3 install ."
script:
  - "python zipfly/test.py"
sudo: false
