language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:  
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"  
install:
  - "pip3 install zipfly"
script:
  - python zipfly/test.py
sudo: false